apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.namespace}}
  labels:
    app: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
    spec:
      containers:
      - name: {{ .Values.deployment.name }}
        image: {{ .Values.deployment.spec.image }}
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: {{ .Values.containers.resources.requests.cpu}}
            memory: {{ .Values.containers.resources.requests.memory}}
          limits:
            cpu: {{ .Values.containers.resources.limits.cpu }}
            memory: {{ .Values.containers.resources.limits.memory }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              {{- range .Values.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms }}
              - matchExpressions:
                  {{- range .matchExpressions }}
                  - key: {{ .key }}
                    operator: {{ .operator }}
                    values:
                      {{- range .values }}
                        - {{ . }}
                      {{- end }}
                  {{- end }}
              {{- end }}
      